# global
OUTDIR: "SuRE-pipelineOutput"
ADPT_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAA"
ADPTR_IPCR_FORW_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAACCAGTGAT"
ADPTR_IPCR_REV_SEQ: "CCAGTCGT"

CUTMOTIF_CATG: &CUTMOTIF_CATG 
  "CATG"
CUTMOTIF_TCGA: &CUTMOTIF_TGCA 
  "TGCA"
CUTMOTIF_NONE: &CUTMOTIF_NONE
  ""

SuRE42_GID: &SURE42_GID
  "HG02601"
SuRE43_GID: &SURE43_GID
  "NA18983"
SuRE44_GID: &SURE44_GID
  "HG01241"
SuRE45_GID: &SURE45_GID
  "HG03464"
GID: *SURE45_GID

BOWTIE2_REFSEQ: "$HOME/data/bowtie2-indexes/hg19_ch1-22_XYM"
MAX_INSERT_LENGTH: 1000
NCORES: 30
ASSEMBLY: "hg19"

cDNA:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/cDNA/"
  OUTDIR:
    "cDNA"
  SAMPLES:
    SuRE23_45_B1_T1:
      - 3520_1_12_1_RNA_45_5_K562_SuRE23_TFrep1_PCRrep1_pgcDNA_adapter_2_150604_hg_CAGATCA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T2:
      - 3520_2_12_2_RNA_45_5_K562_SuRE23_TFrep1_PCRrep2_pgcDNA_adapter_2_150604_hg_ACTTGAA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T3:
      - 3520_3_12_3_RNA_45_6_K562_SuRE23_TFrep2_PCRrep1_pgcDNA_adapter_2_150604_hg_GATCAGA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T4:
      - 3520_4_12_4_RNA_45_6_K562_SuRE23_TFrep2_PCRrep2_pgcDNA_adapter_2_150604_hg_TAGCTTA_L002_R1_001.fastq.gz
    SuRE23_55_B2_T1:
      - 3875_1_16_1_RNA_55_5_K562_SuRE23_PCRrep1_ATCACGA_S63_L008_R1_001.fastq.gz
    SuRE23_55_B2_T2:
      - 3875_2_16_2_RNA_55_5_K562_SuRE23_PCRrep2_CGATGTA_S64_L008_R1_001.fastq.gz

plDNA:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/plDNA/"
  OUTDIR:
    "plDNA"
  SAMPLES:
    plDNA.1:
      - 3419_29_10_29_Sce1_plDNA_SuRE23_PCRrep1_TACCTTA_L002_R1_001.fastq.gz
    plDNA.2:
      - 3419_30_10_30_Sce1_plDNA_SuRE23_PCRrep2_CTGTGTA_L002_R1_001.fastq.gz

iPCR:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/iPCR/"
  OUTDIR:
    "iPCR"
  SAMPLES:
    iPCR_3262_2: 
      R1: 3262_2_SuRE23_iPCR_1_CGATGTA_L001_R1_001.fastq.gz
      R2: 3262_2_SuRE23_iPCR_1_CGATGTA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_3: 
      R1: 3262_3_SuRE23_iPCR_2_TTAGGCA_L001_R1_001.fastq.gz
      R2: 3262_3_SuRE23_iPCR_2_TTAGGCA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_4: 
      R1: 3262_4_SuRE23_iPCR_3_TGACCAA_L001_R1_001.fastq.gz
      R2: 3262_4_SuRE23_iPCR_3_TGACCAA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_5: 
      R1: 3262_5_SuRE23_iPCR_4_ACAGTGA_L001_R1_001.fastq.gz
      R2: 3262_5_SuRE23_iPCR_4_ACAGTGA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3262_6: 
      R1: 3262_6_SuRE23_iPCR_5_GCCAATA_L001_R1_001.fastq.gz
      R2: 3262_6_SuRE23_iPCR_5_GCCAATA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_1: 
      R1: 3336_1_150122_SuRE23_iPCR_1_CGATGTA_R1_001.fastq.gz
      R2: 3336_1_150122_SuRE23_iPCR_1_CGATGTA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_2: 
      R1: 3336_2_150122_SuRE23_iPCR_2_TTAGGCA_R1_001.fastq.gz
      R2: 3336_2_150122_SuRE23_iPCR_2_TTAGGCA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_3: 
      R1: 3336_3_150122_SuRE23_iPCR_3_TGACCAA_R1_001.fastq.gz
      R2: 3336_3_150122_SuRE23_iPCR_3_TGACCAA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_4: 
      R1: 3336_4_150122_SuRE23_iPCR_4_ACAGTGA_R1_001.fastq.gz
      R2: 3336_4_150122_SuRE23_iPCR_4_ACAGTGA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3336_5: 
      R1: 3336_5_150122_SuRE23_iPCR_5_GCCAATA_R1_001.fastq.gz
      R2: 3336_5_150122_SuRE23_iPCR_5_GCCAATA_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_2_L001: 
      R1: 3466_2_SuRE23_iPCR_1_CGATGTA_L001_R1_001.fastq.gz
      R2: 3466_2_SuRE23_iPCR_1_CGATGTA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_2_L002: 
      R1: 3466_2_SuRE23_iPCR_1_CGATGTA_L002_R1_001.fastq.gz
      R2: 3466_2_SuRE23_iPCR_1_CGATGTA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_3_L001: 
      R1: 3466_3_SuRE23_iPCR_2_TTAGGCA_L001_R1_001.fastq.gz
      R2: 3466_3_SuRE23_iPCR_2_TTAGGCA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_3_L002: 
      R1: 3466_3_SuRE23_iPCR_2_TTAGGCA_L002_R1_001.fastq.gz
      R2: 3466_3_SuRE23_iPCR_2_TTAGGCA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_4_L001: 
      R1: 3466_4_SuRE23_iPCR_3_TGACCAA_L001_R1_001.fastq.gz
      R2: 3466_4_SuRE23_iPCR_3_TGACCAA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_4_L002: 
      R1: 3466_4_SuRE23_iPCR_3_TGACCAA_L002_R1_001.fastq.gz
      R2: 3466_4_SuRE23_iPCR_3_TGACCAA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_5_L001: 
      R1: 3466_5_SuRE23_iPCR_4_ACAGTGA_L001_R1_001.fastq.gz
      R2: 3466_5_SuRE23_iPCR_4_ACAGTGA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_5_L002: 
      R1: 3466_5_SuRE23_iPCR_4_ACAGTGA_L002_R1_001.fastq.gz
      R2: 3466_5_SuRE23_iPCR_4_ACAGTGA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_6_L001: 
      R1: 3466_6_SuRE23_iPCR_5_GCCAATA_L001_R1_001.fastq.gz
      R2: 3466_6_SuRE23_iPCR_5_GCCAATA_L001_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_3466_6_L002: 
      R1: 3466_6_SuRE23_iPCR_5_GCCAATA_L002_R1_001.fastq.gz
      R2: 3466_6_SuRE23_iPCR_5_GCCAATA_L002_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_CATG
    iPCR_HpyCH4V_phusion_1: 
      R1: 3761_1_SuRE23_HpyCH4V_phusion_1_ACTTGAA_L008_R1_001.fastq.gz
      R2: 3761_1_SuRE23_HpyCH4V_phusion_1_ACTTGAA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
    iPCR_HpyCH4V_phusion_2: 
      R1: 3761_2_SuRE23_HpyCH4V_phusion_2_GATCAGA_L008_R1_001.fastq.gz
      R2: 3761_2_SuRE23_HpyCH4V_phusion_2_GATCAGA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
    iPCR_HpyCH4V_kappa_1: 
      R1: 3761_3_SuRE23_HpyCH4V_kappa_1_TAGCTTA_L008_R1_001.fastq.gz
      R2: 3761_3_SuRE23_HpyCH4V_kappa_1_TAGCTTA_L008_R2_001.fastq.gz
      CUTMOTIF: *CUTMOTIF_TGCA
